# Support the author by using one of the funding links below.
# Maintained by Bart van Tuijn (https://bartvantuijn.nl)

# GitHub Sponsors
github: bartvantuijn

# Buy Me a Coffee
buy_me_a_coffee: bartvantuijn

# Your support helps me keep building useful tools, open-source projects, and tutorials.
